version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydbCR
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
        - ./postgresql:/var/lib/postgresql/data
